module(..., package.seeall)
_G[_modname or (...)] = _M
_G.MODULE_FLAGS = {
    watchdog = true,
    uart_bridge = true,
    t3x_app = true,
    t3x_wakeup = true,
    t3x_policy = true,
    gpio = true,
    pmd_runtime = false,
    charge = true,
    mqtt = true,
    battery = true,
    battery_guard = true,
    sound_prompt = true,
    time_sync = true,
    sntp = true,
    mobile_info = false,  -- 已移出 lib/；2005→1005 仍可用；恢复见 archive/slim/README.md
    cellular = true,
    fota = true,
    rndis = (_G.FEATURE_CFG and _G.FEATURE_CFG.rndis) == true,
    low_power = (_G.FEATURE_CFG and _G.FEATURE_CFG.low_power) ~= false,
    host_evt = (_G.FEATURE_CFG and _G.FEATURE_CFG.host_evt) ~= false,
}
_G.APP_EVENTS = {
    PIR_HW_TRIGGERED = "pir_hw_triggered",
    GPIO_PIR_TRIGGERED = "gpio_pir_triggered",
    GPIO_VBUS_CHANGED = "gpio_vbus_changed",
    GPIO_USB_DET_CHANGED = "gpio_usb_det_changed",
    GPIO_CHG_STATE_CHANGED = "gpio_chg_state_changed",
    GPIO_PWRKEY_SHORT = "gpio_pwrkey_short",
    GPIO_PWRKEY_LONG = "gpio_pwrkey_long",
    GPIO_BOOTKEY_SHORT = "gpio_bootkey_short",
    GPIO_BOOTKEY_LONG = "gpio_bootkey_long",
    GPIO_COPROC_READY = "gpio_coproc_ready",
    POWER_ENTER_REST = "power_enter_rest",
    POWER_EXIT_REST = "power_exit_rest",
    POWER_ENTERED_REST = "power_entered_rest",
    POWER_EXITED_REST = "power_exited_rest",
    MQTT_SERVER_DATA = "mqtt_server_data",
    MQTT_PUBLISH_WAKEUP = "mqtt_publish_wakeup",
    MQTT_PUBLISH_REST = "mqtt_publish_rest",
    MQTT_OFFLINE = "mqtt_offline",
    MQTT_CONNECTED = "mqtt_connected",
    MQTT_STATUS_INTERVAL_CHANGED = "mqtt_status_interval_changed",
    MQTT_USB_RECOVERY_CHANGED = "mqtt_usb_recovery_changed",
    DEVICE_OTA_REQUEST = "device_ota_request",
    MQTT_OTA_STATUS = "mqtt_ota_status",
    DEVICE_REBOOT_REQUEST = "device_reboot_request",
    DEVICE_POWER_OFF_REQUEST = "device_power_off_request",
    PIR_WAKE_T3X = "pir_wake_t3x",
    PIR_MEDIA_EFFECTIVE = "pir_media_effective",
    PIR_REQUEST_T3X_STOP = "pir_request_t3x_stop",
    T3X_SNAPSHOT_DONE = "t3x_snapshot_done",
    PIR_TAKE_PHOTO = "pir_take_photo",
    PIR_RECORD_VIDEO = "pir_record_video",
    PIR_STOP_RECORDING = "pir_stop_recording",
    T3X_RECORD_ACTIVE = "t3x_record_active",
    T3X_RECORD_STOP = "t3x_record_stop",
    T3X_IPC_ALERT = "t3x_ipc_alert",
    T3X_PERSON_CNT = "t3x_person_cnt",
    PIR_TIMER_EXPIRED = "pir_timer_expired",
    UART_RX_RAW = "uart_rx_raw",
    UART_RX_STRING = "uart_rx_string",
    UART_RX_HEX = "uart_rx_hex",
    HOST_UART_FIRST_AT = "host_uart_first_at",
    HOST_NET_ID_P2P = "host_net_id_p2p",
    HOST_NET_ID_GB28181 = "host_net_id_gb28181",
}
return _M
